addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.16")
addSbtPlugin("io.spray" % "sbt-revolver" % "0.9.1")
addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.5.4")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.1.5" )
addSbtPlugin("pl.project13.scala" % "sbt-jmh" % "0.3.7")
